- name: Expense frontend setup
  hosts: all
  become: yes
  tasks: 
    - name: disable the nodejs
      ansible.builtin.shell: dnf module disable nodejs -y
    - name: enable nodejs
      ansible.builtin.shell: dnf module enable nodejs -y
    - name: install the nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: copy the backend.service file
      ansible.builtin.copy:
         src: backend.service
         dest: /etc/systemd/system/backend.service
    - name: adding the user application
      ansible.builtin.user:
        name: expense 
    - name: delete the old content
      ansible.builtin.file:
        path: /app
        state: absent
    - name:
      ansible.builtin.file:
        path: /app
        state: directory
    - name:
      ansible.builtin.unarchive:
      src: /tmp/backend.zip https://expense-artifacts.s3.amazonaws.com/backend.zip 
      dest: /app
      remote_src: yes
    - name: dependency install
      ansible.builtin.shell: npm install
      args:
        chdir: /app
    - name: install mysql
      ansible.builtin.dnf:
        name: mysql
        state: present
    - name: Load schema
      ansible.builtin.shell: mysql -h mysql.osdevops99.online -uroot -p${{MYSQL_ROOT_PASSWORD}} < /app/schema/backend.sql
    - name: starting the backend service
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enabled: yes
        daemon-reload: yes